#version: '3.8'
name: MyTgBot #这个名字是docker-compose容器的名字
services:
  #放可执行文件不是目录
  app:
    build: . #Docker Compose 会在当前目录下查找 Dockerfile 文件，并且依据该文件来构建一个新的镜像。 .表示当前目录
    #command: ["/app/main"] #它表示在容器启动时，会执行 /app/main 这个可执行文件（dockerfile里面写的有这里可以注释掉）
    image: tgbot:v1.0 # 指定镜像名称和标签
    container_name: tgbot # 指定容器名称
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 挂载主机的时间配置文件
    ports:
      - "5000:5000"
