system:
  name: "配置文件里面的name1123"

tgbot:
  Token: "7384710909:AAEGcRFtwuMnoqaCOLA_vRvDE2zcN7ISblI"
  chatID: -1002421880670     # app群chatID: -4102331731   测试Rebot群 ：-1002421880670
  hour: 11                   # 晚上18点
  min: 33                   # 39分
  sec: 11                    #秒